CREATE TABLE "HR"."NOTICE" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
CREATE TABLE HR.RECOMMEND (
	RE_NO NUMBER(38,0),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(100),
	WRITER VARCHAR2(100)
)

DROP TABLE RECOMMEND

CREATE TABLE HR.RECOMMEND (
	RE_NO NUMBER(38,0),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(100),
	WRITER VARCHAR2(100)
)

ALTER TABLE RECOMMEND DROP COLUMN VIEWCOUNT;

CREATE TABLE "HR"."BOARD3" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"WRITEDATE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )
   
ALTER TABLE BOARD3 MODIFY WRITER VARCHAR(200)

ALTER TABLE BOARD3 DROP COLUMN VIEWCOUNT

ALTER TABLE BOARD3 ADD TEST2 VARCHAR(100)

DROP TABLE BOARD3

DROP TABLE BBS2

-- DCL: DB 관리/제어해주는 문법(계정생성, 계정권한부여, 백업, 복구)

CREATE USER apple IDENTIFIED BY a1234

GRANT CONNECT, RESOURCE, DBA TO apple

CREATE TABLE "HR"."PRODUCT3" 
   ("ID" VARCHAR2(100) PRIMARY key, 
	"NAME" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"PRICE" NUMBER(38,0)
   )

INSERT INTO MEMBER VALUES ('100', '100', 'park', '011')

INSERT INTO MEMBER VALUES ('200', '200', 'park', '011')

INSERT INTO MEMBER VALUES ('300', '300', 'park', '011')

SELECT * FROM MEMBER

SELECT * FROM MEMBER WHERE ID = '100' --ID가 100인 모든 컬럼

SELECT ID, NAME FROM MEMBER WHERE ID = '100' --ID가 100인 ID, NAME 컬럼

SELECT NAME, ID AS 아이디 FROM MEMBER WHERE ID = '100'

SELECT TEL FROM MEMBER WHERE NAME = 'park'

UPDATE MEMBER SET NAME = 'kim' WHERE ID = '100'

UPDATE MEMBER SET NAME = 'yang' WHERE ID = '200'

UPDATE MEMBER SET NAME = 'lee' WHERE ID = '300'

UPDATE MEMBER SET PW = '8888', TEL = '9999' WHERE ID = 'ice'

DELETE FROM MEMBER WHERE ID = '100'

DELETE FROM MEMBER WHERE TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' AND TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' OR TEL = '011'

SELECT * FROM MEMBER ORDER BY ID --오름차순

SELECT * FROM MEMBER ORDER BY ID DESC --내림차순



SELECT * FROM PRODUCT ORDER BY PRICE DESC

SELECT NAME, CONTENT, PRICE FROM PRODUCT ORDER BY COMPANY 

SELECT NAME, PRICE FROM PRODUCT WHERE ID = '100'

SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE = '5000'

SELECT NAME, IMG FROM PRODUCT WHERE ID = '100' AND PRICE = '1000'

SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY = 'c100'

SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY = 'c100' OR COMPANY = 'c200'

UPDATE PRODUCT SET CONTENT = '품절' WHERE PRICE = '5000'

UPDATE PRODUCT SET IMG = '0.png', PRICE = '10000' WHERE ID = '100' OR ID = '102'

UPDATE PRODUCT SET COMPANY = 'apple', NAME = 'appleshoes' WHERE ID = '101'

DELETE FROM PRODUCT WHERE NAME = 'shoes1' OR ID = '107'

DELETE FROM PRODUCT WHERE COMPANY = 'c100'

DELETE FROM PRODUCT

DROP TABLE PRODUCT

